name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: run the thing
      uses: NFIBrokerage/delete-artifact@v0.0.8
      with:
        run_id: ${{ github.run_id }}
        name: "release-artifact"
        access_token: ${{ secrets.ACCESS_TOKEN }}
