name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: run the thing
      uses: "NFIBrokerage/delete-artifact@${{ github.sha }}"
